### ISSUE TITLE
Cloudflare does not support this simple URL update method

### ISSUE THREAD

**Issue by jsntn** [fbrettnich/Cloudflare-DDNS#2]
This will be nice, however, Cloudflare currently does not support this simple URL update method.

https://community.cloudflare.com/t/update-dynamic-ip-through-a-url/337257/3

**Comment by fbrettnich** [comment]
Hi, have you read the README? You have to host the [`ddns.php`](https://github.com/fbrettnich/cloudflare-dyndns-php/blob/main/ddns.php) on your own webserver and then you can update your IP address via your own URL. So your webserver acts as a kind of proxy to the Cloudflare API.

**Comment by jsntn** [comment]
Hi! Yes I read that but I didn't see the `ddns.php` implementation there. 

Just looked through that file, now I understood. 

Thanks for your reply!
